[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/aeokiller"
  to = "/aeokiller/"
  status = 301

[[redirects]]
  from = "/aeokiller/*"
  to = "/aeokiller/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
