export const profile = {
  name: "Ismail Bettoumi",
  location: "Doha, Qatar",
  phone: "+974-70773838",
  whatsapp: "https://wa.me/97470773838",
  linkedin: "https://www.linkedin.com/in/ismail-bettoumi-868b04402/",
  email: "bettoumi001@gmail.com",
  tagline: "Digital Marketing & Growth Specialist",
  intro:
    "3+ years scaling B2B & B2C brands across SEO, paid media, AEO, and e-commerce.",
};
export const projects = {
  seo: {
    title: "AEO & SEO Strategy",
    desc: "Technical SEO, topic clusters, and position-zero capture for lasting organic growth.",
    icon: "seo",
  },
  paidmedia: {
    title: "Paid Advertising — Google & Meta Ads",
    desc: "Full-funnel Google & Meta campaigns with audience testing and ROAS control.",
    icon: "paidmedia",
  },
  shopify: {
    title: "E-commerce & Shopify CRO",
    desc: "Storefront UX, product page design, and checkout conversion rate optimization.",
    icon: "shopify",
  },
  email: {
    title: "Email Marketing & Lifecycle Automation",
    desc: "HubSpot & Mailchimp drip workflows and segmentation driving top-tier open rates.",
    icon: "email",
  },
  analytics: {
    title: "AI & Analytics Automation",
    desc: "GA4 attribution dashboards and automated reporting pipelines via Claude API.",
    icon: "analytics",
  },
  aeo: {
    title: "AEO & GEO Strategy",
    desc: "Generative search optimization across ChatGPT, Perplexity, and Claude for AI citations.",
    icon: "aeo",
  },
};

export const strategyShowcases = {
  seo: {
    tag: "SEO & ORGANIC GROWTH",
    category: "CASE // GOOGLE SEARCH · ORGANIC VISIBILITY · SEO",
    title: "Growing Organic Search Visibility",
    subtitle: "Technical SEO, Topic Clusters & Search Intent Optimization",
    metaLine: "Confidential Client · SEO Strategy · Organic Search · 6 Months",
    accent: "#3a53ed",
    verifiedBadge: "SEO CASE STUDY",
    topKpis: [
      { value: "+32%", label: "ORGANIC TRAFFIC", sub: "12K → 16.5K monthly sessions" },
      { value: "41%", label: "FEATURED SNIPPETS", sub: "Target commercial search queries" },
      { value: "+18%", label: "POSITION-ZERO LIFT", sub: "Search intent & Q&A capture rate" },
      { value: "+12%", label: "REVENUE UPLIFT", sub: "Launch window sales contribution" },
    ],
    pillars: [
      {
        num: "PILLAR 01",
        badge: "SEARCH INTENT",
        title: "Search Intent & Topic Mapping",
        desc: "Mapped priority topics around user intent and commercial relevance.",
      },
      {
        num: "PILLAR 02",
        badge: "CONTENT STRATEGY",
        title: "Topic-Cluster Content",
        desc: "Built interconnected content around priority search themes.",
      },
      {
        num: "PILLAR 03",
        badge: "TECHNICAL SEO",
        title: "Technical SEO",
        desc: "Improved site structure, internal linking and technical search visibility.",
      },
      {
        num: "PILLAR 04",
        badge: "PERFORMANCE",
        title: "Measurement & Optimization",
        desc: "Tracked organic traffic, rankings and search performance over time.",
      },
    ],
    ctaSubject: "SEO & Organic Growth Strategy",
    ctaMessage: "Hi Ismail, let's talk about SEO and organic growth.",
  },
  paidmedia: {
    tag: "PAID MEDIA & PERFORMANCE ADS",
    category: "CASE // GOOGLE ADS · META ADS · E-COMMERCE",
    title: "Paid Media & ROAS Optimization",
    subtitle: "Audience Restructuring, Creative Testing & Conversion Funnels",
    metaLine: "Confidential Client · Paid Media Strategy · E-commerce / D2C · 90 Days",
    accent: "#ff6b35",
    verifiedBadge: "PAID MEDIA CASE STUDY",
    topKpis: [
      { value: "-22%", label: "CAC REDUCTION", sub: "Blended acquisition cost" },
      { value: "3.4x", label: "IMPROVED ROAS", sub: "Meta & Google Ads campaigns" },
      { value: "+27%", label: "SALES UPLIFT", sub: "Within 90-day scaling window" },
      { value: "90 Days", label: "TIMEFRAME", sub: "Audience & creative testing window" },
    ],
    pillars: [
      {
        num: "PILLAR 01",
        badge: "AUDIENCE",
        title: "Audience Restructuring",
        desc: "Refined custom and lookalike segmentation across Meta and Google Ads.",
      },
      {
        num: "PILLAR 02",
        badge: "CREATIVE TESTING",
        title: "Creative Testing",
        desc: "Deployed a systematic ad variation testing framework to combat ad fatigue.",
      },
      {
        num: "PILLAR 03",
        badge: "FUNNEL OPTIMIZATION",
        title: "Funnel Optimization",
        desc: "Aligned ad messaging with landing pages to boost overall conversion rates.",
      },
    ],
    ctaSubject: "Paid Advertising & Media Buying Strategy",
    ctaMessage: "Hi Ismail, let's talk about Paid Advertising and ROAS optimization.",
  },
  shopify: {
    tag: "E-COMMERCE & STOREFRONT CRO",
    category: "CASE // SHOPIFY RETAIL BRANDS",
    title: "Shopify Conversion Rate Optimization",
    subtitle: "Storefront UX, Funnel Audits & Checkout Optimization",
    accent: "#10b981",
    verifiedBadge: "6 Retail Brands (Verified)",
    topKpis: [
      { value: "+31%", label: "CONVERSION RATE LIFT", sub: "Average across 6 retail brands" },
      { value: "1.8% → 2.4%", label: "BASELINE CONVERSION", sub: "Direct storefront lift" },
      { value: "1.8x → 3.9x", label: "E-COMMERCE ROAS", sub: "Scaled over 12 months" },
      { value: "6 Brands", label: "FUNNELS OVERHAULED", sub: "UX & speed optimized" },
    ],
    pillars: [
      {
        num: "PILLAR 01",
        badge: "FUNNEL AUDIT",
        title: "Shopify Architecture & UX Enhancements",
        desc: "Restructured navigation across 6 retail brands, lifting conversion rates from 1.8% to 2.4% (+31%).",
      },
      {
        num: "PILLAR 02",
        badge: "PRODUCT PAGES",
        title: "High-Converting Product Page Design",
        desc: "Optimized product pages, mobile UX, and trust signals to eliminate checkout hesitation.",
      },
      {
        num: "PILLAR 03",
        badge: "PAGE SPEED",
        title: "Page Speed & Checkout Friction Reduction",
        desc: "Streamlined theme assets and checkout steps to cut drop-off from cart to payment.",
      },
      {
        num: "PILLAR 04",
        badge: "COHORT ATTRIBUTION",
        title: "Attribution Audits & Spend Reallocation",
        desc: "Reallocated media spend to top-converting shopper cohorts, scaling ROAS to 3.9x.",
      },
    ],
    ctaSubject: "Shopify CRO & E-commerce Strategy",
  },
  email: {
    tag: "LIFECYCLE & RETENTION",
    category: "CASE // HUBSPOT · MAILCHIMP",
    title: "Lifecycle Email Marketing & Drip Automation",
    subtitle: "Automated Drips, Retention & Launch Alignment",
    accent: "#6366f1",
    verifiedBadge: "Verified Campaign Data",
    topKpis: [
      { value: "34%", label: "EMAIL OPEN RATE", sub: "+13 pts above 21% benchmark" },
      { value: "+29%", label: "LAUNCH REVENUE LIFT", sub: "Paid, email & SEO sync" },
      { value: "+42%", label: "INBOUND LEADS", sub: "85 → 120+/quarter in 2 quarters" },
      { value: "100%", label: "AUTOMATED DRIPS", sub: "HubSpot & Mailchimp sequences" },
    ],
    pillars: [
      {
        num: "PILLAR 01",
        badge: "AUTOMATED DRIPS",
        title: "Automated Lifecycle Drip Workflows",
        desc: "Built automated nurture workflows in HubSpot and Mailchimp to drive sustained repeat sales.",
      },
      {
        num: "PILLAR 02",
        badge: "OPEN RATE OPTIMIZATION",
        title: "Benchmark-Beating Open Rates (34%)",
        desc: "Optimized subject lines and delivery timing, achieving a 34% open rate (+13 pts above benchmark).",
      },
      {
        num: "PILLAR 03",
        badge: "OMNICHANNEL SYNC",
        title: "Product Launch Synchronization",
        desc: "Aligned email drops with paid and organic campaigns to generate a 29% revenue lift.",
      },
      {
        num: "PILLAR 04",
        badge: "INBOUND PIPELINE",
        title: "Integrated Acquisition & Lead Nurturing",
        desc: "Integrated email capture with search funnels, growing qualified inbound leads by 42%.",
      },
    ],
    ctaSubject: "Email Lifecycle & Automation Strategy",
  },
  aeo: {
    tag: "AI CITATIONS & GENERATIVE SEARCH",
    category: "CASE // AEO · GOOGLE AI OVERVIEWS · PERPLEXITY",
    title: "Answer Engine Optimization (AEO & GEO)",
    subtitle: "AI Citations, Structured Schema & Position-Zero Authority",
    accent: "#3a53ed",
    verifiedBadge: "7 Clients & Enterprise Brand (Verified)",
    topKpis: [
      { value: "+36%", label: "AI & ZERO-CLICK IMPRESSIONS", sub: "Average increase across 7 clients" },
      { value: "+44%", label: "POSITION-ZERO LIFT", sub: "Conversational Q&A capture rate" },
      { value: "+28%", label: "BRAND CITATION SHARE", sub: "Google AI Overviews & Perplexity" },
      { value: "41%", label: "FEATURED SNIPPETS", sub: "Targeted commercial keywords" },
    ],
    pillars: [
      {
        num: "PILLAR 01",
        badge: "CONVERSATIONAL Q&A",
        title: "Conversational Q&A Content Structuring",
        desc: "Restructured content into conversational Q&A formats, boosting position-zero capture by 44%.",
      },
      {
        num: "PILLAR 02",
        badge: "STRUCTURED SCHEMA",
        title: "Conversational & Speakable Schema Markup",
        desc: "Deployed FAQ and speakable schema across 7 domains, boosting AI impressions by 36%.",
      },
      {
        num: "PILLAR 03",
        badge: "GENERATIVE ENGINES",
        title: "AI Overview & Perplexity Optimization",
        desc: "Optimized brand footprints for ChatGPT and Perplexity, growing citation share by 28%.",
      },
      {
        num: "PILLAR 04",
        badge: "FEATURED SNIPPETS",
        title: "Commercial Entity Snippet Domination",
        desc: "Secured featured snippets on 41% of commercial queries via clear entity markup.",
      },
    ],
    ctaSubject: "Aevis & AEO Strategy",
    singleCta: true,
    ctaLabel: "Let's talk about Aevis",
    ctaMessage: "Hi Ismail, let's talk about Aevis.",
  },
  aeocase: {
    tag: "AI CITATIONS & GENERATIVE SEARCH",
    category: "CASE // GOOGLE AI OVERVIEWS · PERPLEXITY · CHATGPT",
    title: "Growing Brand Visibility Across AI Search",
    subtitle: "Answer Engine Optimization, Structured Schema & Position-Zero Capture",
    metaLine: "Confidential Client · AEO Strategy · AI Search · 6 Months",
    accent: "#3a53ed",
    verifiedBadge: "AEO CASE STUDY",
    topKpis: [
      { value: "+16%", label: "AI IMPRESSIONS", sub: "Average increase across client domains" },
      { value: "+20%", label: "POSITION-ZERO LIFT", sub: "Conversational Q&A capture rate" },
      { value: "41%", label: "FEATURED SNIPPETS", sub: "Targeted commercial search queries" },
      { value: "+14%", label: "CITATION SHARE", sub: "Google AI Overviews & Perplexity AI" },
    ],
    pillars: [
      {
        num: "PILLAR 01",
        badge: "AI AUDIT & INTENT",
        title: "Query Mapping & Citation Audit",
        desc: "Audit target queries and brand visibility across AI search.",
      },
      {
        num: "PILLAR 02",
        badge: "CONTENT ARCHITECTURE",
        title: "Direct-Answer & Q&A Formatting",
        desc: "Restructured content for clearer answers and easier extraction.",
      },
      {
        num: "PILLAR 03",
        badge: "STRUCTURED DATA",
        title: "Entity & Conversational Schema",
        desc: "Improved structured data and entity signals for machine-readable content.",
      },
      {
        num: "PILLAR 04",
        badge: "MEASUREMENT & OPTIMIZATION",
        title: "Measurement & Optimization",
        desc: "Tracked AI visibility, citations and search performance.",
      },
    ],
    ctaSubject: "AEO & AI Search Strategy",
  },
  seocase: {
    tag: "SEO & ORGANIC GROWTH",
    category: "CASE // GOOGLE SEARCH · ORGANIC VISIBILITY · SEO",
    title: "Growing Organic Search Visibility",
    subtitle: "Technical SEO, Topic Clusters & Search Intent Optimization",
    metaLine: "Confidential Client · SEO Strategy · Organic Search · 6 Months",
    accent: "#3a53ed",
    verifiedBadge: "SEO CASE STUDY",
    topKpis: [
      { value: "+32%", label: "ORGANIC TRAFFIC", sub: "12K → 16.5K monthly sessions" },
      { value: "41%", label: "FEATURED SNIPPETS", sub: "Target commercial search queries" },
      { value: "+18%", label: "POSITION-ZERO LIFT", sub: "Search intent & Q&A capture rate" },
      { value: "+12%", label: "REVENUE UPLIFT", sub: "Launch window sales contribution" },
    ],
    pillars: [
      {
        num: "PILLAR 01",
        badge: "SEARCH INTENT",
        title: "Search Intent & Topic Mapping",
        desc: "Mapped priority topics around user intent and commercial relevance.",
      },
      {
        num: "PILLAR 02",
        badge: "CONTENT STRATEGY",
        title: "Topic-Cluster Content",
        desc: "Built interconnected content around priority search themes.",
      },
      {
        num: "PILLAR 03",
        badge: "TECHNICAL SEO",
        title: "Technical SEO",
        desc: "Improved site structure, internal linking and technical search visibility.",
      },
      {
        num: "PILLAR 04",
        badge: "PERFORMANCE",
        title: "Measurement & Optimization",
        desc: "Tracked organic traffic, rankings and search performance over time.",
      },
    ],
    ctaSubject: "SEO & Organic Growth Strategy",
    ctaMessage: "Hi Ismail, let's talk about SEO and organic growth.",
  },
  paidmediacase: {
    tag: "PAID MEDIA & PERFORMANCE ADS",
    category: "CASE // GOOGLE ADS · META ADS · E-COMMERCE",
    title: "Paid Media & ROAS Optimization",
    subtitle: "Audience Restructuring, Creative Testing & Conversion Funnels",
    metaLine: "Confidential Client · Paid Media Strategy · E-commerce / D2C · 90 Days",
    accent: "#ff6b35",
    verifiedBadge: "PAID MEDIA CASE STUDY",
    topKpis: [
      { value: "-22%", label: "CAC REDUCTION", sub: "Blended acquisition cost" },
      { value: "3.4x", label: "IMPROVED ROAS", sub: "Meta & Google Ads campaigns" },
      { value: "+27%", label: "SALES UPLIFT", sub: "Within 90-day scaling window" },
      { value: "90 Days", label: "TIMEFRAME", sub: "Audience & creative testing window" },
    ],
    pillars: [
      {
        num: "PILLAR 01",
        badge: "AUDIENCE",
        title: "Audience Restructuring",
        desc: "Refined custom and lookalike segmentation across Meta and Google Ads.",
      },
      {
        num: "PILLAR 02",
        badge: "CREATIVE TESTING",
        title: "Creative Testing",
        desc: "Deployed a systematic ad variation testing framework to combat ad fatigue.",
      },
      {
        num: "PILLAR 03",
        badge: "FUNNEL OPTIMIZATION",
        title: "Funnel Optimization",
        desc: "Aligned ad messaging with landing pages to boost overall conversion rates.",
      },
    ],
    ctaSubject: "Paid Advertising & Media Buying Strategy",
    ctaMessage: "Hi Ismail, let's talk about Paid Advertising and ROAS optimization.",
  },
  analytics: {
    tag: "AI AUTOMATION & GA4 ATTRIBUTION",
    category: "CASE // CLAUDE API · GA4 · LOOKER STUDIO",
    title: "AI Automation & Attribution Intelligence",
    subtitle: "Claude API Pipelines, GA4 Dashboards & Attribution Audits",
    accent: "#a855f7",
    verifiedBadge: "Production Workflows (Verified)",
    topKpis: [
      { value: "-58%", label: "CYCLE TIME REDUCTION", sub: "Claude & Anthropic API automation" },
      { value: "6 hrs/wk", label: "SAVED PER WEEK", sub: "Automated GA4 dashboards" },
      { value: "5+ hrs/mo", label: "SAVED PER CLIENT", sub: "Eliminated manual reporting" },
      { value: "1.8x → 3.9x", label: "ROAS GAIN", sub: "Attribution audit reallocations" },
    ],
    pillars: [
      {
        num: "PILLAR 01",
        badge: "CLAUDE AI PIPELINES",
        title: "Claude & Anthropic API Automation",
        desc: "Automated reporting workflows with Claude and Anthropic API, reducing cycle time by 58%.",
      },
      {
        num: "PILLAR 02",
        badge: "GA4 DASHBOARDS",
        title: "Automated GA4 Reporting Dashboards",
        desc: "Built real-time GA4 dashboards, eliminating 6 hours per week of manual reporting.",
      },
      {
        num: "PILLAR 03",
        badge: "CLIENT EFFICIENCY",
        title: "Reporting Time Savings (5+ hrs/client)",
        desc: "Replaced slide decks with automated KPI pipelines, saving 5+ hours per client monthly.",
      },
      {
        num: "PILLAR 04",
        badge: "ATTRIBUTION AUDITS",
        title: "Cross-Channel Attribution Audits",
        desc: "Conducted monthly attribution audits to redirect spend into top-ROAS cohorts, reaching 3.9x ROAS.",
      },
    ],
    ctaSubject: "Analytics & AI Automation Strategy",
  },
};

export const aeoKiller = {
  name: "Aevis",
  kicker: "Autonomous AI Agent",
  headline: "Be the brand AI recommends.",
  value:
    "Ensures your brand is cited and recommended when buyers search across ChatGPT, Perplexity, or Claude.",
  href: "/aeokiller/?code=1212",
  benefits: [
    {
      icon: "radar",
      title: "Live Citation Radar",
      desc: "Monitor brand visibility and citation share across AI search engines in real time.",
    },
    {
      icon: "gap",
      title: "Competitor Intelligence",
      desc: "Identify competitor gaps and uncover queries where your brand can win citations.",
    },
    {
      icon: "agent",
      title: "Autonomous Optimization",
      desc: "Continuously optimize structured knowledge so answer engines cite your brand first.",
    },
  ],
};
export const aevis = aeoKiller;

export const products = [
  {
    key: "aevis",
    title: "Aevis",
    tagline: "AI Citation Audit & Brand Visibility Platform",
    desc: "Dark-mode conversion architecture, live citation audit UI, and automated lead funnels.",
    icon: "aevis",
    logo: "/assets/logos/aevis.png",
    isFlagship: true,
    tags: ["Flagship Venture", "Conversion Design", "AI SaaS"],
    accent: "#3a53ed",
    href: "/aeokiller/",
  },
  {
    key: "nexus",
    title: "Nexus Website Manager",
    tagline: "Browser Workspace & Reference Organizer",
    desc: "Local-first browser workspace turning saved links and daily discovery into four clear views.",
    icon: "nexus",
    logo: "/assets/logos/nexus.png",
    tags: ["Landing Pages", "UI/UX Design", "CRO"],
    accent: "#8b5cf6",
    href: "/projects/nexus/index.html",
  },
  {
    key: "prepflow",
    title: "PrepFlow",
    tagline: "Nutrition & Weekly Meal Prep Experience",
    desc: "Mobile onboarding and meal prep UX built for frictionless fitness subscriber acquisition.",
    icon: "prepflow",
    logo: "/assets/logos/prepflow.png",
    tags: ["Mobile Landing", "UI/UX Design", "Funnel Design"],
    accent: "#d8ff55",
    href: "/projects/prepflow/index.html",
  },
  {
    key: "promptilo",
    title: "Promptilo",
    tagline: "Visual AI Prompt & Resource Directory",
    desc: "Bento-grid directory organizing curated AI prompts, workflows, and tools with clean IA.",
    icon: "promptilo",
    logo: "/assets/logos/promptilo.png",
    tags: ["Design Systems", "Web UI", "Information Architecture"],
    accent: "#7a82ff",
    href: "/projects/promptilo/index.html",
  },
  {
    key: "skinny",
    title: "Skinny",
    tagline: "Calm Daily Skincare & Habit Timeline",
    desc: "Minimalist iOS interface uniting skincare, supplements, and routines with zero clutter.",
    icon: "skinny",
    logo: "/assets/logos/skinny.png",
    tags: ["Visual Hierarchy", "iOS UI/UX", "Product Craft"],
    accent: "#8d4c79",
    href: "/projects/skinny/index.html",
  },
  {
    key: "timer-gym",
    title: "Timer Gym",
    tagline: "High-Contrast Tactical Workout Timer",
    desc: "Glanceable interval workout interface driven by voice, audio cues, and haptics.",
    icon: "timer-gym",
    logo: "/assets/logos/timer-gym.png",
    tags: ["Design Ergonomics", "Tactile UI", "Mobile App"],
    accent: "#a9f76d",
    href: "/projects/timer-gym/index.html",
  },
  {
    key: "voicy",
    title: "Voicy",
    tagline: "Native macOS Voice-to-Text Layer",
    desc: "Apple HIG menu bar utility turning speech into clean, formatted text with zero clutter.",
    icon: "voicy",
    logo: "/assets/logos/voicy.png",
    tags: ["Apple HIG", "Desktop UI", "Productivity Design"],
    accent: "#8a70ff",
    href: "/projects/voicy/index.html",
  },
];

export const experience = [
  {
    year: "2025",
    route: "DOH",
    company: "Independent",
    initial: "I",
    href: "https://www.linkedin.com/in/ismail-bettoumi-868b04402/",
    current: true,
    role: "Digital Marketing Consultant",
    dates: "Jan 2025 — Present",
    desc: "Directing full-funnel marketing for 11 clients ($45k+ quarterly spend). Scaled ROAS from 1.8x to 3.9x, grew AI citations by 36% via AEO, and lifted Shopify conversions by 31%.",
    projects: ["aeo", "shopify", "analytics"],
  },
  {
    year: "2024",
    company: "Andalus Smart Way",
    initial: "A",
    href: "https://www.linkedin.com/in/ismail-bettoumi-868b04402/",
    role: "Senior Marketing Specialist",
    dates: "Jan 2024 — Dec 2024",
    desc: "Grew organic traffic 18k → 26.5k (+47%) in 6 months via topic clusters and technical SEO. Captured snippets on 41% of target keywords and lifted Google Ads Quality Score from 4 to 8.",
    projects: ["seo"],
  },
  {
    year: "2023",
    route: "ALG",
    company: "Zer",
    initial: "Z",
    href: "https://www.linkedin.com/in/ismail-bettoumi-868b04402/",
    role: "Marketing Specialist",
    dates: "Jan 2023 — Dec 2023",
    desc: "Increased B2B inbound leads by 42% (85 → 120+/qtr). Ran 14 PPC tests cutting CAC by 23% and CPC by 27%, achieved 34% email open rates, and managed $9.5k/mo spend on target.",
    projects: ["paidmedia", "email"],
  },
];

export const cvData = {
  summary:
    "Data-driven Digital Marketing Specialist with 3+ years of experience scaling B2B & B2C brands across SEO, paid media, CRO, and analytics.",
  skills: [
    {
      category: "SEO & Generative Search (AEO)",
      items: [
        "Technical SEO",
        "Schema & Structured Data (FAQ/HowTo/Speakable)",
        "Google AI Overviews & Perplexity Optimization",
        "Position-Zero Capture",
        "Google Search Console",
      ],
    },
    {
      category: "Paid Media & Acquisition",
      items: [
        "Google Ads",
        "Meta Ads (FB/IG)",
        "Audience Segmentation & Retargeting",
        "Multi-variant A/B Testing",
        "Quality Score Optimization",
        "ROAS & CAC Control",
      ],
    },
    {
      category: "E-commerce & CRO",
      items: [
        "Shopify Store Architecture",
        "Product Listing Optimization",
        "Funnel Optimization",
        "Checkout UX Improvements",
        "Conversion Rate Optimization (CRO)",
      ],
    },
    {
      category: "Lifecycle & AI Automation",
      items: [
        "HubSpot & Mailchimp",
        "Automated Email Drips",
        "Claude & Anthropic API Workflows",
        "Google Analytics 4 (GA4)",
        "Executive Dashboards & Attribution",
      ],
    },
  ],
  education: [
    {
      degree: "Master’s Degree in Physics Education",
      institution: "Higher School of Teachers, Algeria",
      year: "2025",
    },
    {
      degree: "Bachelor’s Degree in Science & Technology",
      institution: "Higher School of Teachers, Algeria",
      year: "2020",
      details: "Secondary School Teaching Certificate included",
    },
  ],
  certifications: [
    {
      title: "Google Digital Marketing & E-commerce Certificate",
      issuer: "Google (via Coursera)",
      date: "March 2026",
      desc: "8-course credential: Full-Funnel Omnichannel Strategy, SEO/SEA, E-commerce Store Management, Analytics & Marketing Automation.",
    },
  ],
};
